### ISSUE TITLE
Refactor list functions of nfd pkg

### ISSUE THREAD

**Issue by kononovn** [openshift-kni/eco-goinfra#116]
Refactor list functions. Use https://github.com/openshift-kni/eco-goinfra/blob/main/pkg/pod/list.go as example

**Comment by trewest** [comment]
@kononovn It doesn't seem like the nfd package has the typical list functionality of other pkgs. I think we can close this one.

**Comment by kononovn** [comment]
@trewest Agree. Closing this issue
