### ISSUE TITLE
Refactor List functions to take an optional ListOptions argument

### ISSUE THREAD

**Issue by trewest** [openshift-kni/eco-goinfra#140]
The following package's List functions should include an option v1.ListOptions or goclient.ListOptions argument depending on the client

Deployment
NMState
NTO
SRIOV
MCO

**Comment by ElaiShalevRH** [comment]
created a PR: (https://github.com/openshift-kni/eco-goinfra/pull/177)

**Comment by ElaiShalevRH** [comment]
PR https://github.com/openshift-kni/eco-goinfra/pull/177 Merged
