### ISSUE TITLE
Add a README that explains how to build and run the tests

### ISSUE THREAD

**Issue by zedr** [openshift-kni/eco-goinfra#2]
As a user, I would like to know how to build and execute one or more tests provided by this package. Thanks!

**Comment by kononovn** [comment]
@zedr This project doesn't provide test cases/test suites. It provides access to test infrastructure that can be imported to any other project. Basically it's a set of shareable libraries.  We are working on README which will describe how to re-use this infra.

**Comment by zedr** [comment]
Understood. Thanks. I'll close this then.
