### ISSUE TITLE
Add ICSP package in to the main branch to pkg/iscp

### ISSUE THREAD

**Issue by kononovn** [openshift-kni/eco-goinfra#78]
Package location: /pkg/icsp.go

ImageContentSourcePolicy package should support the following public api:

Builder: struct

- [x] NewBuilder - Creates role object with single mirror. Basic struct
- [x] WithRepositoryDigestMirror - Appends additional mirrors to basic struct.
- [x] Create - Creates ImageContentSourcePolicy Rule on a cluster.
- [x] Delete - Deletes ImageContentSourcePolicy Rule on from cluster.
- [x] Update - Updates ImageContentSourcePolicy Rule on a cluster.
- [x] Exists - Check if particular rule exist in cluster.

**Comment by vkolodny** [comment]
@kononovn please assign me to this task - I cannot autoassign

**Comment by vkolodny** [comment]
@trewest @kononovn  Do we need all ***AndWait functions here ?
